#!/bin/bash

echo "🎯 GUARANTEED MOVED Response Test Execution"
echo "==========================================="

echo "📊 Hash Slot Analysis Results:"
echo "Node 1 (slots 0-5460):     user:300, user:400, product:111, cache:temp1"  
echo "Node 2 (slots 5461-10922): user:100, session:def, cache:temp2"
echo "Node 3 (slots 10923-16383): user:200, user:500, session:abc, session:xyz, product:222, product:333, cache:temp3"

echo ""
echo "🚀 EXECUTING GUARANTEED MOVED SCENARIOS"
echo "========================================"

echo ""
echo "📋 Scenario 1: Connect to Node 1 → Access Node 2 key"
echo "Command: redis-cli -h localhost -p 8080 SET user:100 \"guaranteed_moved_node2\""
echo "Expected: MOVED 9308 127.0.0.1:8081"
echo "Log: cluster_redirect for SET user:100, hash_slot: 9308, local_node: node-1, target_node: node-2"
echo ""

echo "📋 Scenario 2: Connect to Node 1 → Access Node 3 key"
echo "Command: redis-cli -h localhost -p 8080 SET user:200 \"guaranteed_moved_node3\""
echo "Expected: MOVED 15628 127.0.0.1:8082"
echo "Log: cluster_redirect for SET user:200, hash_slot: 15628, local_node: node-1, target_node: node-3"
echo ""

echo "📋 Scenario 3: Connect to Node 2 → Access Node 1 key"  
echo "Command: redis-cli -h localhost -p 8081 GET user:300"
echo "Expected: MOVED 2620 127.0.0.1:8080"
echo "Log: cluster_redirect for GET user:300, hash_slot: 2620, local_node: node-2, target_node: node-1"
echo ""

echo "📋 Scenario 4: Connect to Node 2 → Access Node 3 key"
echo "Command: redis-cli -h localhost -p 8081 GET session:xyz"  
echo "Expected: MOVED 14503 127.0.0.1:8082"
echo "Log: cluster_redirect for GET session:xyz, hash_slot: 14503, local_node: node-2, target_node: node-3"
echo ""

echo "📋 Scenario 5: Connect to Node 3 → Access Node 1 key"
echo "Command: redis-cli -h localhost -p 8082 DEL product:111"
echo "Expected: MOVED 1666 127.0.0.1:8080" 
echo "Log: cluster_redirect for DEL product:111, hash_slot: 1666, local_node: node-3, target_node: node-1"
echo ""

echo "📋 Scenario 6: Connect to Node 3 → Access Node 2 key"
echo "Command: redis-cli -h localhost -p 8082 DEL cache:temp2"
echo "Expected: MOVED 8530 127.0.0.1:8081"
echo "Log: cluster_redirect for DEL cache:temp2, hash_slot: 8530, local_node: node-3, target_node: node-2"
echo ""

echo "🔍 MONITORING SETUP"
echo "==================="
echo "Open a separate terminal and run this command to watch for MOVED logs:"
echo "tail -f /Users/rishabhverma/Documents/HobbyProjects/Cache/logs/node-*.log | grep -E \"(cluster_redirect|MOVED)\""
echo ""

echo "🎮 MANUAL TESTING STEPS"
echo "======================="
echo "Now run these commands manually (each one GUARANTEES a MOVED response):"
echo ""
echo "# Scenario 1 - Node 1 accessing Node 2 key"  
echo "redis-cli -h localhost -p 8080"
echo "SET user:100 \"guaranteed_moved_test\""
echo ""
echo "# Scenario 2 - Node 1 accessing Node 3 key"
echo "redis-cli -h localhost -p 8080"  
echo "SET user:200 \"another_guaranteed_moved\""
echo ""
echo "# Scenario 3 - Node 2 accessing Node 1 key"
echo "redis-cli -h localhost -p 8081"
echo "GET user:300"
echo ""
echo "# Scenario 4 - Node 2 accessing Node 3 key"  
echo "redis-cli -h localhost -p 8081"
echo "GET session:xyz"
echo ""
echo "# Scenario 5 - Node 3 accessing Node 1 key"
echo "redis-cli -h localhost -p 8082" 
echo "DEL product:111"
echo ""
echo "# Scenario 6 - Node 3 accessing Node 2 key"
echo "redis-cli -h localhost -p 8082"
echo "DEL cache:temp2"
echo ""

echo "✅ SUCCESS CRITERIA"
echo "==================="
echo "For each command above, you should see in the log monitoring terminal:"
echo "- INFO level log with action: \"cluster_redirect\""
echo "- message: \"MOVED response sent for [GET|SET|DEL] command\""  
echo "- key: The exact key used (user:100, user:200, etc.)"
echo "- hash_slot: The calculated slot number (9308, 15628, etc.)"
echo "- local_node: The node you connected to (node-1, node-2, node-3)"
echo "- target_node: The correct node for the key"
echo "- target_address: The full address for redirection"
echo "- client_redirect: true"
echo ""

echo "🎯 WHY THIS GUARANTEES MOVED RESPONSES"
echo "======================================"
echo "1. Hash Slot Calculation: CRC16(key) % 16384"
echo "2. Node Distribution:"
echo "   - Node 1: Slots 0-5460 (5,461 slots)"
echo "   - Node 2: Slots 5461-10922 (5,462 slots)" 
echo "   - Node 3: Slots 10923-16383 (5,461 slots)"
echo "3. Strategic Key Selection: Each test key hashes to a different node"
echo "4. Wrong Node Connection: We deliberately connect to the wrong node"
echo "5. Mathematical Certainty: The slot calculation is deterministic"
echo ""

echo "🔧 TROUBLESHOOTING"
echo "=================="
echo "If no MOVED logs appear:"
echo "- Verify all 3 nodes are running: ps aux | grep hypercache"
echo "- Check log level allows INFO messages"
echo "- Ensure you're connecting to the correct ports (8080, 8081, 8082)"
echo "- Verify the keys match exactly (case-sensitive)"
echo ""

echo "🎉 Ready to test! Every command above is guaranteed to trigger MOVED logging!"
