apiVersion: 1

datasources:
  - name: HyperCache Logs
    type: elasticsearch
    access: proxy
    url: http://hypercache-elasticsearch:9200
    database: "hypercache-logs"
    isDefault: true
    jsonData:
      interval: Daily
      timeField: "@timestamp"
      esVersion: "8.11.0"
      maxConcurrentShardRequests: 5
      logMessageField: "message"
      logLevelField: "level"
      includeFrozen: false
      xpack: false
    readOnly: false
